services:
  - type: web
    name: shopify-swym-relay
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_SCOPES
        value: read_products,write_products,read_customers,write_customers,read_orders,write_orders
      - key: SHOPIFY_APP_URL
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
    autoDeploy: true
    branch: main
    rootDir: ./

